dist: xenial
language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install: pip install 'tox-travis ~= 0.12.0'
script: tox
jobs:
  include:
  - name: Static Analysis
    python: '3.8'
    script: tox -e static
deploy:
  provider: pypi
  user: __token__
  password:
    secure: DkOVCB/fNUCjfeuS9sLhQ9bGeBAtpPxlFFB2fxgpYCCFtASk6cjQeCgDCdcntq5iAJAO2KamQS57LVO6sx6vI9YBBlBt0jLq7O+wWq8TU0jIt+4YXIQ0MDXQArCdBNuCq7ZMx23INXSPoIpiNsb8UaLTh5airukPDMWlUOX/1Y3i8jatvxWHmp0pjC+oXdD7QuzT1dDkuu/PlWXVtlbvlRaoSClDnw6ySkDuxzhsuXJ9XjcXCkYoyTA6HrZzAkJXOqOioTUtjS8XHu21VL12w3f3ABxHcFVAOH2qS47z9UzwgtX0aM2Qk0TG0nD6B3VL9WMhQgUC3gsE0rNC61w+ijL11c73MPon6kjsqBmNwq+QVcc6jIPDELP+eeaShLhx6khnNo7poGvl9HH3T/arhzFa5hB8je55gzlccmwjGUCBISDHVD59AwY15AQV92utnmRRU3e8Taw/hh5FOJE53Z5ux2Fd4N6mwEZt4MYh7+nnBckatKFjuzJ84YQACZK0u3lMeZaXIqrQLVVDZE3eR5WhuJvWHN87DJ6UPnmNxad0Fc90+N7SZgs38iFGwIkdFWKxgH1IDegW11NS3lJXngwe/3YJ24pMJu72R5X0p89F2ULoqORM1W73VzeOE6uGK0F2gVDEhAEQXhXvzho0kod8lPsjP5AnHEm7hSrK6xE=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    repo: dbader/pytest-mypy
    tags: true
    python: '3.4'
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
